import {MultiplayerClient} from '@rmc/multiplayer-client';
import versionText from '../../version.txt?raw';
import {GameInput} from './input.js';
import {createDungeonView} from './view.js';
import './style.css';
const base=import.meta.env.BASE_URL,classes=[['warrior','Warrior','Heavy axe'],['valkyrie','Valkyrie','Armored shield'],['wizard','Wizard','Arcane burst'],['elf','Elf','Swift bow']];
document.querySelector('#app').innerHTML=`
<div class="ambience"></div><header class="corner top-left"><span class="eyebrow">RMC · COOPERATIVE ARCADE</span><h1>GAUNTLET <em>3D</em></h1><p>Four heroes. One way out.</p></header>
<nav class="corner top-right"><a href="https://github.com/SamuelAsherRivello/babylon-lite-gauntlet-clone-3d" target="_blank" rel="noreferrer">Source ↗</a><button id="help">How to play</button></nav>
<aside class="lore"><span class="ornament">◇</span><span class="eyebrow">A DESCENT INTO</span><h2>The<br>Hollow<br><em>Keep</em></h2><div class="rule"></div><p>Break the summoning altars.<br>Claim the forgotten key.<br>Escape together.</p><div class="enemy-list"><span>01 / GHOSTS</span><span>02 / GRUNTS</span><span>03 / DEMONS</span><span>04 / LOBBERS</span></div><span class="edition">ONE DUNGEON · 1–4 PLAYERS</span></aside>
<main id="game" aria-label="Gauntlet dungeon"><div class="game-header"><div><span class="eyebrow">LEVEL 01</span><h2>The Hollow Keep</h2></div><span id="connection">LOADING</span></div><div class="objectives"><span id="altars">◇ ALTARS 0 / 4</span><span id="key">⚿ FIND THE KEY</span><span id="score">0 GOLD</span></div>
<div id="viewport"><canvas id="canvas" aria-label="3D dungeon. WASD or arrows to move, Space to attack, E for magic." tabindex="0"></canvas><div id="labels"></div><canvas id="minimap" width="126" height="150" aria-label="Dungeon map"></canvas><div id="notice" role="status">Preparing the dungeon…</div>
<div class="touch-controls"><div id="stick" role="group" aria-label="Movement joystick"><span id="knob"></span></div><div class="action-controls"><button id="magic" aria-label="Cast magic">✦<small id="magic-label">MAGIC</small></button><button id="attack" aria-label="Attack">⚔<small>ATTACK</small></button></div></div>
<div id="overlay" class="overlay"><div class="sigil">◇</div><h2 id="overlay-title">Opening the keep</h2><p id="overlay-text">Loading original 3D models…</p><button id="overlay-action" hidden>Retry connection</button></div></div>
<section class="player-hud"><div class="health-row"><span id="identity">Joining the party</span><span id="health-text">— / —</span></div><div class="health-track"><div id="health-bar"></div></div><div class="choose-label"><span>SWITCH HERO</span><small>INSTANT · KEEP YOUR HEALTH</small></div><div class="classes">${classes.map(([id,name,detail],i)=>`<button class="class-button" data-class="${id}" aria-label="Switch to ${name}" aria-pressed="false"><span class="keycap">${i+1}</span><img src="${base}assets/${id}.png" alt=""><strong>${name}</strong><small>${detail}</small></button>`).join('')}</div></section></main>
<aside class="party-panel"><span class="eyebrow">YOUR FELLOWSHIP</span><h2>Better together.</h2><div id="party"></div><button id="invite">Copy game link ↗</button><p class="party-tip">Friends open the same link to hot join. Everyone can pick the same hero.</p><div class="controls-guide"><div><kbd>W A S D</kbd><span>Move</span></div><div><kbd>SPACE</kbd><span>Attack · auto-aim</span></div><div><kbd>E</kbd><span>Magic burst</span></div><div><kbd>1 – 4</kbd><span>Switch hero</span></div></div></aside>
<footer class="corner bottom-left"><button id="pause">Ⅱ Pause controls</button><button id="fullscreen">⛶ Fullscreen</button></footer><div class="corner bottom-right"><span>ORIGINAL BLENDER ART · WEBGPU</span><b id="version">v${versionText.trim().split('=')[1]}</b></div>
<dialog id="help-dialog"><button id="close-help" aria-label="Close instructions">✕</button><span class="eyebrow">WELCOME, ADVENTURER</span><h2>Escape the Hollow Keep</h2><p>Destroy all four glowing summoning altars, collect the gold key, then reach the teal gate in the north. Food restores health; chests award gold.</p><p><b>WASD / arrows</b> to move. Hold <b>Space</b> to fire at the nearest visible enemy or altar. <b>E</b> releases a magic burst every 10 seconds. On touch screens, drag the joystick and hold Attack.</p><p>Switch heroes with the four buttons or keys <b>1–4</b>. Your colored ring and player number stay the same. Switching preserves your health percentage.</p><p>Ghosts chase, grunts strike, demons shoot, and lobbers mark an area before their bombs land. Step out of red circles.</p><p>Pause stops your controls only; the shared world keeps moving. If you fall, surviving allies can finish. After victory or defeat, the lowest player number can restart.</p><small>Sessions are temporary. Reconnecting creates a fresh player; a server restart resets the dungeon.</small></dialog>`;
const $=id=>document.getElementById(id),input=new GameInput(),session=new MultiplayerClient(import.meta.env.VITE_SERVER_URL||'https://rmc-colyseus-multiplayer-server.vercel.app','gauntlet-3d');
let view,ready=false,fatal='',eventSerial=-1,localPause=false,noticeTimer,partySignature='';
function overlay(title,text,action){$('overlay').hidden=false;$('overlay-title').textContent=title;$('overlay-text').textContent=text;$('overlay-action').hidden=!action;if(action){$('overlay-action').textContent=action.text;$('overlay-action').onclick=action.run;}}
function clear(){input.clear();$('knob').style.transform='';$('attack').classList.remove('held');$('magic').classList.remove('held');session.send('input',input.read());}
function pause(value){localPause=value;input.paused=value;clear();$('pause').textContent=value?'▶ Resume controls':'Ⅱ Pause controls';update(session.state);}
const choose=name=>session.send('class',name);
document.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>choose(b.dataset.class));$('pause').onclick=()=>pause(!localPause);
$('help').onclick=()=>{$('help-dialog').showModal();pause(true);};$('close-help').onclick=()=>{$('help-dialog').close();pause(false);};$('help-dialog').addEventListener('cancel',()=>pause(false));
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{$('notice').textContent='Fullscreen is unavailable in this browser.';}};
$('invite').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);$('invite').textContent='Link copied ✓';}catch{$('invite').textContent='Share this page’s address';}};
window.addEventListener('keydown',e=>{if($('help-dialog').open)return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'&&!e.repeat){pause(!localPause);return;}if(/^Digit[1-4]$/.test(e.code)&&!e.repeat)choose(classes[Number(e.code.slice(-1))-1][0]);input.keys.add(e.code);});
window.addEventListener('keyup',e=>input.keys.delete(e.code));window.addEventListener('blur',clear);document.addEventListener('visibilitychange',()=>{if(document.hidden)clear();});
let stickPointer=null;
function stickMove(e){if(stickPointer!==e.pointerId)return;const r=$('stick').getBoundingClientRect();let x=(e.clientX-r.left-r.width/2)/32,z=(e.clientY-r.top-r.height/2)/32;const n=Math.max(1,Math.hypot(x,z));x/=n;z/=n;input.touches.x=x;input.touches.z=z;$('knob').style.transform=`translate(${x*26}px,${z*26}px)`;}
$('stick').onpointerdown=e=>{e.preventDefault();stickPointer=e.pointerId;$('stick').setPointerCapture(e.pointerId);stickMove(e);};$('stick').onpointermove=stickMove;
for(const evt of ['pointerup','pointercancel','lostpointercapture'])$('stick').addEventListener(evt,e=>{if(stickPointer===e.pointerId){stickPointer=null;input.touches.x=input.touches.z=0;$('knob').style.transform='';session.send('input',input.read());}});
for(const id of ['attack','magic']){const b=$(id);b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);input.touches[id]=true;b.classList.add('held');};for(const evt of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(evt,()=>{input.touches[id]=false;b.classList.remove('held');session.send('input',input.read());});}
const timer=setInterval(()=>session.send('input',input.read()),50);
function minimap(g){const c=$('minimap').getContext('2d');c.clearRect(0,0,126,150);g.level.forEach((row,z)=>[...row].forEach((v,x)=>{c.fillStyle=v==='#'?'#567079':'#1b292c';c.fillRect(x*6,z*6,5,5);}));for(const a of g.generators){c.fillStyle=a.hp>0?'#d5aa5d':'#345449';c.fillRect(a.x*6-2,a.z*6-2,5,5);}c.fillStyle='#64e6d0';c.fillRect(58,6,10,4);for(const p of g.players){c.fillStyle=p.color;c.beginPath();c.arc(p.x*6,p.z*6,3,0,Math.PI*2);c.fill();}}
function update(state){
 const g=state.gameState,p=g?.players.find(p=>p.id===state.sessionId);$('connection').textContent=state.status==='connected'?`${state.players.length}/4 ONLINE`:state.status.toUpperCase();$('connection').classList.toggle('online',state.status==='connected');
 if(fatal){overlay('WebGPU unavailable',fatal,{text:'Reload',run:()=>location.reload()});return;}if(!ready)return;
 if(state.status!=='connected'){overlay(state.status==='full'?'The party is full':'Joining the fellowship',state.error||'Connecting to the shared dungeon…',{text:'Retry connection',run:()=>session.connect()});return;}if(!g)return;
 view?.setState(g,state.sessionId);minimap(g);
 if(g.event.serial!==eventSerial){eventSerial=g.event.serial;$('notice').textContent=g.event.text;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>{$('notice').textContent='Break the altars · Find the key · Reach the north gate';},4200);}
 $('altars').textContent=`◇ ALTARS ${g.generators.filter(a=>a.hp<=0).length} / 4`;$('key').textContent=g.key?'⚿ KEY FOUND':'⚿ FIND THE KEY';$('key').classList.toggle('complete',g.key);$('score').textContent=`${g.players.reduce((n,p)=>n+p.score,0)} GOLD`;
 if(p){$('identity').textContent=`P${p.number} · ${p.className.toUpperCase()}`;$('identity').style.color=p.color;$('health-text').textContent=`${Math.ceil(p.hp)} / ${p.maxHp}`;$('health-bar').style.width=`${p.hp/p.maxHp*100}%`;$('health-bar').style.background=p.color;$('magic-label').textContent=p.magicCooldown>0?`${Math.ceil(p.magicCooldown)}s`:'MAGIC';document.querySelectorAll('[data-class]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.class===p.className));b.disabled=p.hp<=0;});}
 const signature=g.players.map(p=>`${p.id}:${p.className}:${Math.ceil(p.hp)}`).join('|');if(signature!==partySignature){partySignature=signature;$('party').replaceChildren();for(let i=1;i<=4;i++){const hero=g.players.find(p=>p.number===i),row=document.createElement('div');row.className='party-slot'+(hero?' occupied':'');if(hero){row.style.setProperty('--player',hero.color);row.innerHTML=`<span class="seat">${i}</span><div><b>${hero.className.toUpperCase()} ${hero.id===state.sessionId?'<small>YOU</small>':''}</b><div class="party-health"><i style="width:${hero.hp/hero.maxHp*100}%"></i></div></div><span>${Math.ceil(hero.hp)}</span>`;}else row.innerHTML=`<span class="seat">${i}</span><div>Waiting for a hero<small>HOT JOIN AVAILABLE</small></div>`;$('party').append(row);}}
 if(g.phase!=='playing'){const leader=[...g.players].sort((a,b)=>a.number-b.number)[0];overlay(g.phase==='victory'?'The keep is conquered':'The fellowship has fallen',g.phase==='victory'?'All four altars are broken. Your party escaped together.':'Try a different hero, share the food, and watch for red bomb circles.',leader?.id===state.sessionId?{text:'Begin another descent',run:()=>{clear();session.send('restart');}}:null);if(leader?.id!==state.sessionId)$('overlay-text').textContent+=` Waiting for P${leader?.number} to restart.`;}
 else if(p?.hp<=0)overlay('You have fallen','Your allies can still escape. Restart becomes available when the party finishes or everyone falls.');
 else if(localPause)overlay('Controls paused','The dungeon keeps moving for everyone. You can still take damage.',{text:'Resume',run:()=>pause(false)});else $('overlay').hidden=true;
}
session.subscribe(update);
try{view=await createDungeonView($('canvas'),$('labels'),base);ready=true;session.connect();}catch(error){console.error(error);fatal='This game needs WebGPU and hardware acceleration. Try an up-to-date Chrome or Edge, then reload. '+(error.message||'');ready=true;update(session.state);}
window.addEventListener('pagehide',()=>{clearInterval(timer);session.disconnect();view?.dispose();},{once:true});
window.gameDiagnostics={get state(){return session.state;},get ready(){return ready;},get input(){return input.read();}};
