import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const url=process.env.GAME_URL||'http://127.0.0.1:5186/babylon-lite-gauntlet-clone-3d/';
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-webgpu']});
const errors=[];
async function open(options={}){const context=await browser.newContext({viewport:{width:1440,height:1000},...options});const page=await context.newPage();page.on('pageerror',e=>{errors.push(e.message);console.error(e.message);});page.on('console',m=>{if(m.type()==='error')console.error(m.text());});await page.goto(url);await page.waitForFunction(()=>window.gameDiagnostics?.state.status==='connected'&&window.gameDiagnostics.state.gameState,{},{timeout:45000});return {context,page};}
const read=page=>page.evaluate(()=>window.gameDiagnostics.state);
try{
 const a=await open(),b=await open();
 for(const name of ['warrior','valkyrie','wizard','elf']){await a.page.locator(`[data-class="${name}"]`).click();await a.page.waitForFunction(n=>window.gameDiagnostics.state.gameState.players.find(p=>p.id===window.gameDiagnostics.state.sessionId).className===n,name);}
 await a.page.locator('[data-class="wizard"]').click();await b.page.locator('[data-class="wizard"]').click();await a.page.waitForTimeout(350);assert((await read(a.page)).gameState.players.every(p=>p.className==='wizard'));
 await a.page.locator('[data-class="valkyrie"]').click();await b.page.locator('[data-class="valkyrie"]').click();await a.page.waitForTimeout(400);
 let state=await read(a.page),g=state.gameState;assert.equal(g.players.length,2);assert(g.players.every(p=>p.className==='valkyrie'));assert.equal(new Set(g.players.map(p=>p.color)).size,2);
 await a.page.screenshot({path:'project-name/documentation/game-desktop.png'});
 await b.context.close();await a.page.bringToFront();
 const before=(await read(a.page)).gameState.players[0].x;await a.page.keyboard.down('d');await a.page.waitForTimeout(400);await a.page.keyboard.up('d');assert((await read(a.page)).gameState.players[0].x>before+.3);
 await a.page.locator('#pause').click();await a.page.keyboard.down('w');assert.equal((await a.page.evaluate(()=>window.gameDiagnostics.input)).z,0);await a.page.keyboard.up('w');await a.page.locator('#overlay-action').click();
 await a.page.keyboard.down('w');await a.page.evaluate(()=>window.dispatchEvent(new Event('blur')));assert.equal((await a.page.evaluate(()=>window.gameDiagnostics.input)).z,0);await a.page.keyboard.up('w');
 function next(level,p,t){const start=[Math.round(p.x),Math.round(p.z)],goal=[Math.round(t.x),Math.round(t.z)],queue=[start],seen=new Set([start.join()]),prev=new Map();while(queue.length){const v=queue.shift();if(v.join()===goal.join()){let n=v;while(prev.has(n.join())&&prev.get(n.join()).join()!==start.join())n=prev.get(n.join());return {x:n[0],z:n[1]};}for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1]]){const n=[v[0]+dx,v[1]+dz];if(level[n[1]]?.[n[0]]==='.'&&!seen.has(n.join())){seen.add(n.join());prev.set(n.join(),v);queue.push(n);}}}return t;}
 const held=new Set();async function keys(wanted){for(const k of held)if(!wanted.has(k)){await a.page.keyboard.up(k);held.delete(k);}for(const k of wanted)if(!held.has(k)){await a.page.keyboard.down(k);held.add(k);}}
 const started=Date.now();while(Date.now()-started<150000){state=await read(a.page);g=state.gameState;if(g.phase!=='playing')break;const p=g.players.find(p=>p.id===state.sessionId);let t=g.generators.filter(v=>v.hp>0).sort((v,w)=>Math.hypot(v.x-p.x,v.z-p.z)-Math.hypot(w.x-p.x,w.z-p.z))[0];if(p.hp<65)t=g.pickups.filter(v=>v.kind==='food').sort((v,w)=>Math.hypot(v.x-p.x,v.z-p.z)-Math.hypot(w.x-p.x,w.z-p.z))[0]||t;t=t||g.pickups.find(v=>v.kind==='key')||{x:10,z:1.5};const n=next(g.level,p,t),wanted=new Set(['Space','e']);if(Math.abs(n.x-p.x)>.16)wanted.add(n.x>p.x?'d':'a');if(Math.abs(n.z-p.z)>.16)wanted.add(n.z>p.z?'s':'w');await keys(wanted);await a.page.waitForTimeout(70);}
 await keys(new Set());assert.equal(g.phase,'victory',JSON.stringify({phase:g.phase,players:g.players,altars:g.generators}));await a.page.screenshot({path:'project-name/documentation/game-victory.png'});await a.page.locator('#overlay-action').click();await a.page.waitForFunction(()=>window.gameDiagnostics.state.gameState.phase==='playing');assert.equal((await read(a.page)).gameState.generators.filter(v=>v.hp>0).length,4);await a.context.close();
 const mobile=await open({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});await mobile.page.screenshot({path:'project-name/documentation/game-mobile.png'});
 const rect=await mobile.page.locator('#stick').boundingBox();const cdp=await mobile.context.newCDPSession(mobile.page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:rect.x+rect.width/2+25,y:rect.y+rect.height/2}]});await mobile.page.waitForTimeout(250);assert((await mobile.page.evaluate(()=>window.gameDiagnostics.input)).x>.5);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await mobile.page.waitForTimeout(100);assert.equal((await mobile.page.evaluate(()=>window.gameDiagnostics.input)).x,0);assert.equal(await mobile.page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await mobile.context.close();
 assert.deepEqual(errors,[]);await fs.writeFile('project-name/documentation/browser-verification.json',JSON.stringify({url,verified:new Date().toISOString(),checks:['two independent clients','same hero and unique colors','keyboard movement','pause','focus loss','full level victory through keyboard only','restart','390x844 layout','emulated touch drag/release'],errors},null,2));console.log('PASS: multiplayer, full level, replay, keyboard and emulated touch');
}finally{await browser.close();}
